version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: images_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d images_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - storage:/storage
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/images_db
      - RABBITMQ_URL=amqp://guest:guest@rabbit:5672/
      - STORAGE_PATH=/storage
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  worker:
    build: .
    command: python app/workers/image_processor.py
    volumes:
      - .:/app
      - storage:/storage
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/images_db
      - RABBITMQ_URL=amqp://guest:guest@rabbit:5672/
      - STORAGE_PATH=/storage
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  storage: